  
name: Deploy Demo Page

on:
  push:
    branches: [master]

jobs:
  deploy-demo-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build useTools
        run: |
          yarn install --frozen-lockfile
          yarn test
          yarn build
      - name: Build example
        run: |
          cd example
          yarn install --frozen-lockfile
          yarn build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: demo
          build_dir: example/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}