name: Beta Publish

on:
  pull_request:
    branches: 
      - master
    types: [closed]

jobs:
  # When a new PR is merged to master branch, a beta version will be published
  publish-beta:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Allow push from action in PAT trigger an action
          persist-credentials: false
      
      - name: Configure Git setting for CI
        run: |
          git config --global user.name "Lineng CAO"
          git config --global user.email "lineng.ca@gmail.com"
      
      - name: Publish beta package to NPMJS npm registry
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Test package
        run: |
          yarn install --frozen-lockfile
          yarn test
      - name: Assign a new beta version from current package version
        run: npm version prerelease --preid=beta -m "ci-chore %s"

      - name: Publish beta to NPMJS
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish beta package to GITHUB npm registry
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: 'vincecao'

      - name: Publish beta to GITHUB
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push beta version change to HEAD:master
        uses: ad-m/github-push-action@master
        with:
          # for re-triggering github checks on master, need to use a personal PAT token instead of GITHUB_TOKEN
          github_token: ${{ secrets.GH_PUSH_COMMIT_TOKEN }}
