name: Stable Publish

# Then a new release is created, a stable version will be published.
on:
  release:
    types:
      - created

jobs:
  publish-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test package
        run: |
          yarn install --frozen-lockfile
          yarn test
      - name: Assign stable version from release tag version
        run: |
          git config --global user.name "Lineng CAO"
          git config --global user.email "lineng.ca@gmail.com"
          npm version ${{ github.event.release.tag_name }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          tag: latest
          token: ${{ secrets.NPM_TOKEN }}
      - name: Update stable version to master branch
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}